# File path specific labels
windows:
  - '**/*_windows.go'

macos:
  - '**/*_darwin.go'

linux:
  - '**/*_linux.go'

cli:
  - '**/cli/**/*'
  - '**/commands/**/*'

documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'website/**/*'
  - 'mkdocs-website/**/*'

templates:
  - '**/templates/**/*'
  - '**/template/**/*'

runtime:
  - '**/runtime/**/*'

bindings:
  - '**/internal/binding/**/*'
  - '**/internal/generator/**/*'

